### ISSUE TITLE
ModuleNotFoundError: No module named 'reclist.datasets'

### ISSUE THREAD

**Issue by EdIzaguirre** [jacopotagliabue/post-modern-data-stack#3]
When attempting to run: "from reclist.datasets import CoveoDataset", I get the error: "ModuleNotFoundError: No module named 'reclist.datasets'". Upon inspecting the GitHub for RecList, it appears that there is no dataset module, and it appears there never has been? How can I resolve this? I can download the dataset and manually upload to Snowflake, but there was a mention of some pre-processing that was done. What pre-processing was this?

**Comment by jacopotagliabue** [comment]
Hi @EdIzaguirre ! Thanks for your message! The original [Reclist](https://reclist.io/) had actually quite a few datasets included for convenience (perhaps they are still available as part of the 1.x package? Sorry, it's been a while now). 

Anyhow, as far as this repo is concerned, the dataset is [here](https://github.com/coveooss/SIGIR-ecom-data-challenge) -this session-level dataset has quite good documentation, so it should be easy to re-use: in the Snowflake script [here](https://github.com/jacopotagliabue/post-modern-stack/blob/8beb2531cb5716fc0cc41b36d9fbe7e8e2c4f53d/upload/upload_to_snowflake.py#L143) you'll find some sample code that goes from the JSON event-level stream of the source dataset, to something that can be uploaded to the warehouse to kick start the process.

It should be straightforward, once you have the original data source, to modify upload to reflect any small change in the data structure you may find. Note that the model is a simple sequence prediction neural net, and as such, the same repo can work with any sequence level data (see for example my NYU [course](https://github.com/jacopotagliabue/MLSys-NYU-2022/tree/main/weeks/13) for another perspective).

**Comment by EdIzaguirre** [comment]
Got it, I was able to download the dataset successfully and get the data uploaded to Snowflake. Thank you.
