### ISSUE TITLE
The source dataset coveo_sigir.zip is not available. [COVEO_INTERACTION_DATASET_S3_URL = 'https://reclist-datasets-6d3c836d-6djh887d.s3.us-west-2.amazonaws.com/coveo_sigir.zip']

### ISSUE THREAD

**Issue by domini1969** [jacopotagliabue/post-modern-data-stack#4]
File Name: \post-modern-stack\.venv\Lib\site-packages\reclist\utils\config.py

The following zip file is not available. 

COVEO_INTERACTION_DATASET_S3_URL = 'https://reclist-datasets-6d3c836d-6djh887d.s3.us-west-2.amazonaws.com/coveo_sigir.zip'

And that leads to the errors:

..\post-modern-stack\.venv\Lib\site-packages\reclist\datasets.py

class CoveoDataset(RecDataset):
    """
    Coveo SIGIR data challenge dataset
    """
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def load(self):
        cache_directory = get_cache_directory()
        filename = os.path.join(cache_directory, "coveo_sigir.zip")  # TODO: make var somewhere

        if not os.path.exists(filename) or self.force_download:
            download_with_progress(COVEO_INTERACTION_DATASET_S3_URL, filename)

        with tempfile.TemporaryDirectory() as temp_dir:
            with zipfile.ZipFile(filename, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            with open(os.path.join(temp_dir, 'dataset.json')) as f:
                data = json.load(f)

        self._x_train = data["x_train"]
        self._y_train = None
        self._x_test = data["x_test"]
        self._y_test = data["y_test"]
        self._catalog = data["catalog"]

**Comment by jacopotagliabue** [comment]
hi @domini1969 , thanks so much for your feedback - it looks like this project is using a very old reference to Reclist, with outdated pointers to embedded datasets within the library. But fear not ;-) A few replacement for you to consider (in the end the dataset is a simple sequential dataset [product1, product2...] with a dictionary catalog {product1: metadata, ...} 👍 

* the original full SIGIR 2021 dataset [here](https://github.com/coveooss/SIGIR-ecom-data-challenge)
* evalRS 2023 music dataset [here](https://github.com/RecList/evalRS-KDD-2023)
* the spotify dataset [here](https://engineering.atspotify.com/2018/05/introducing-the-million-playlist-dataset-and-recsys-challenge-2018/), and introductory slides [here](https://github.com/jacopotagliabue/MLSys-NYU-2022/tree/main/weeks/13) on the intuition behind a sequential model.

Hope this is helpful as you continue your quest!
